extends Node

enum Format {
	CC,
	SAGE,
	LL,
	UPF
}

var classes : Dictionary[String, Class] = {
	"Adjudicator"	: Class.new(0,  "Assassin"),
	"Assassin"		: Class.new(1,  "Assassin"),
	"Bard"			: Class.new(2,  "Assassin"),
	"Brute"			: Class.new(3,  "Assassin"),
	"Generic"		: Class.new(4,  "Assassin"),
	"Guardian"		: Class.new(5,  "Assassin"),
	"Illusionist"	: Class.new(6,  "Assassin"),
	"Mechanologist"	: Class.new(7,  "Assassin"),
	"Merchant"		: Class.new(8,  "Assassin"),
	"Necromancer"	: Class.new(9,  "Assassin"),
	"Ninja"			: Class.new(10, "Assassin"),
	"Pirate"		: Class.new(11, "Assassin"),
	"Ranger"		: Class.new(12, "Assassin"),
	"Runeblade"		: Class.new(13, "Assassin"),
	"Shapeshifter"	: Class.new(14, "Assassin"),
	"Thief"			: Class.new(15, "Assassin"),
	"Warrior"		: Class.new(16, "Assassin"),
	"Wizard"		: Class.new(17, "Assassin"),
}

var talents : Dictionary[String, Talent] = {
	"Chaos"		: Talent.new(0,  "Chaos"),
	"Draconic"	: Talent.new(1,  "Draconic"),
	"Earth"		: Talent.new(2,  "Earth"),
	"Elemental"	: Talent.new(3,  "Elemental"),
	"Ice"		: Talent.new(4,  "Ice"),
	"Light"		: Talent.new(5,  "Light"),
	"Lightning"	: Talent.new(6,  "Lightning"),
	"Mystic"	: Talent.new(7,  "Mystic"),
	"Revered"	: Talent.new(8,  "Revered"),
	"Reviled"	: Talent.new(9,  "Reviled"),
	"Royal"		: Talent.new(10, "Royal"),
	"Shadow"	: Talent.new(11, "Shadow"),
}

var _Hero : Dictionary[String, Hero] = {
	"ArakniS"		: Hero.new(0,   "Arakni, 5L!p3d 7hRu 7h3 cR4X"	  ,  193, 38, ["Assassin"], ["Chaos"], [Format.CC, Format.LL]),
	"Arakni"		: Hero.new(1,   "Arakni, Huntsman"				  ,  274, 40, ["Assassin"], [], [Format.CC, Format.LL]),
	"ArakniM"		: Hero.new(2,   "Arakni, Marionette"			  ,  899, 40, ["Assassin"], ["Chaos"], [Format.CC, Format.LL]),
	"AuroraL"		: Hero.new(3,   "Aurora, Legacy of Tempest"		  ,    0, 40, ["Runeblade"], ["Lightning"], [Format.LL]),
	"Aurora"		: Hero.new(4,   "Aurora, Shooting Star"			  , 1051, 40, ["Runeblade"], ["Elemental"], [Format.CC, Format.LL]),
	"Azalea"		: Hero.new(5,   "Azalea, Ace in the Hole"		  , 1036, 40, ["Ranger"], [], [Format.LL]),
	"Betsy"			: Hero.new(6,   "Betsy, Skin in the Game"		  ,    7, 40, ["Guardian"], [], [Format.CC, Format.LL]),
	"Bravo"			: Hero.new(7,   "Bravo, Showstopper"			  ,  776, 40, ["Guardian"], [], [Format.CC, Format.LL]),
	"Starvo"		: Hero.new(8,   "Bravo, Star of the Show"		  , 1582, 40, ["Guardian"], ["Elemental"], [Format.LL]),
	"Briar"			: Hero.new(9,   "Briar, Warden of Thorns"		  , 1158, 40, ["Runebalde"], ["Elemental"], [Format.LL]),
	"Chane"			: Hero.new(10,  "Chane, Bound by Shadow"		  , 1102, 40, ["Runeblade"], ["Shadow"], [Format.LL]),
	"Cindra"		: Hero.new(11,  "Cindra, Dracai of Retribution"	  ,  880, 40, ["Ninja"], ["Draconic", "Royal"], [Format.CC, Format.LL]),
	"Dio"			: Hero.new(12,  "Dash I/O"						  ,  950, 36, ["Mechanologist"], [], [Format.CC, Format.LL]),
	"Dash"			: Hero.new(13,  "Dash, Inventor Extraordinaire"	  , 1013, 40, ["Mechanologist"], [], [Format.LL]),
	"Dorinthea"		: Hero.new(14,  "Dorinthea Ironsong"			  ,  758, 40, ["Warrior"], [], [Format.CC, Format.LL]),
	"Mortimer"		: Hero.new(15,  "Dr. Mortimer, Blight of the Pits",    0, 40, ["Assassin"], [], [Format.CC, Format.LL]),
	"Dromai"		: Hero.new(16,  "Dromai, Ash Artist"			  , 1096, 40, ["Illusionist"], ["Draconic"], [Format.LL]),
	"Enigma"		: Hero.new(17,  "Enigma, Ledger of Ancestry"	  , 1046, 40, ["Illusionist"], ["Mystic"], [Format.LL]),
	"Fai"			: Hero.new(18,  "Fai, Rising Rebellion"			  ,  893, 40, ["Ninja"], ["Draconic"], [Format.CC, Format.LL]),
	"Fang"			: Hero.new(19,  "Fang, Dracai of Blades"		  ,  153, 40, ["Warrior"], ["Draconic", "Royal"], [Format.CC, Format.LL]),
	"Florian"		: Hero.new(20,  "Florian, Rotwood Harbinger"	  , 1029, 40, ["Runeblade"], ["Elemental"], [Format.LL]),
	"Gravy"			: Hero.new(21,  "Gravy Bones, Shipwrecked Looter" ,  584, 40, ["Necromancer", "Pirate"], [], [Format.CC, Format.LL]),
	"Hala"			: Hero.new(22,  "Hala, Bladesaint of the Vow"	  ,    5, 40, ["Warrior"], [], [Format.CC, Format.LL]),
	"Ira"			: Hero.new(23,  "Ira, Scarlet Revenger"			  ,  131, 40, ["Ninja"], [], [Format.CC, Format.LL]),
	"Iyslander"		: Hero.new(24,  "Iyslander, Stormbind"			  , 1012, 36, ["Wizard"], ["Elemental"], [Format.LL]),
	"Jarl"			: Hero.new(25,  "Jarl Vetreiði"					  ,  268, 40, ["Guardian"], ["Elemental"], [Format.CC, Format.LL]),
	"Kano"			: Hero.new(26,  "Kano, Dracai of Aether"		  , 1028, 30, ["Wizard"], [], [Format.LL]),
	"Kassai"		: Hero.new(27,  "Kassai of the Golden Sand"		  ,  967, 40, ["Warrior"], [], [Format.CC, Format.LL]),
	"Katsu"			: Hero.new(28,  "Katsu, the Wanderer"			  ,  783, 40, ["Ninja"], [], [Format.CC, Format.LL]),
	"Kayo"			: Hero.new(29,  "Kayo, Armed and Dangerous"		  , 1014, 40, ["Brute"], [], [Format.LL]),
	"KayoR"			: Hero.new(30,  "Kayo, Underhanded Cheat"		  ,   29, 40, ["Brute"], ["Reviled"], [Format.CC, Format.LL]),
	"Levia"			: Hero.new(31,  "Levia, Shadowborn Abomination"	  ,  200, 40, ["Brute"], ["Shadow"], [Format.CC, Format.LL]),
	"Lexi"			: Hero.new(32,  "Lexi, Livewire"				  , 1276, 40, ["Ranger"], ["Elemental"], [Format.LL]),
	"Lyath"			: Hero.new(33,  "Lyath Goldmane, Vile Savant"	  ,    3, 40, ["Guardian"], ["Reviled"], [Format.CC, Format.LL]),
	"Malice"		: Hero.new(34,  "Malice, Domina of the Dead"	  ,    0, 40, ["Necromancer"], ["Shadow"], [Format.CC, Format.LL]),
	"Marlynn"		: Hero.new(35,  "Marlynn, Treasure Hunter"		  ,   21, 40, ["Ranger", "Pirate"], [], [Format.CC, Format.LL]),
	"Maxx"			: Hero.new(36,  "Maxx 'The Hype' Nitro"			  ,   85, 40, ["Mechanologist"], [], [Format.CC, Format.LL]),
	"Nuu"			: Hero.new(37,  "Nuu, Alluring Desire"			  , 1004, 40, ["Assassin"], ["Mystic"], [Format.LL]),
	"Oldhim"		: Hero.new(38,  "Oldhim, Grandfather of Eternity" , 1186, 40, ["Guardian"], ["Elemental"], [Format.LL]),
	"Olympia"		: Hero.new(39,  "Olympia, Prized Fighter"		  ,    7, 40, ["Warrior"], [], [Format.CC, Format.LL]),
	"Oscilio"		: Hero.new(40,  "Oscilio, Constella Intelligence" ,  781, 36, ["Wizard"], ["Elemental"], [Format.CC, Format.LL]),
	"OscilioF"		: Hero.new(41,  "Oscilio, Forked Continuum"		  ,    0, 38, ["Wizard"], ["Lightning"], [Format.CC, Format.LL]),
	"Pleiades"		: Hero.new(42,  "Pleiades, Superstar"			  ,   50, 40, ["Guardian"], ["Revered"], [Format.CC, Format.LL]),
	"PrismA"		: Hero.new(43,  "Prism, Awakener of Sol"		  , 1010, 32, ["Illusionist"], ["Light"], [Format.LL]),
	"Prism"			: Hero.new(44,  "Prism, Sculptor of Arc Light"	  , 1098, 40, ["Illusionist"], ["Light"], [Format.LL]),
	"Puffin"		: Hero.new(45,  "Puffin, Hightail"				  ,   43, 40, ["Mechanologist", "Pirate"], [], [Format.CC, Format.LL]),
	"Rhinar"		: Hero.new(46,  "Rhinar, Reckless Rampage"		  ,  362, 40, ["Brute"], [], [Format.CC, Format.LL]),
	"Riptide"		: Hero.new(47,  "Riptide, Lurker of the Deep"	  ,   98, 38, ["Ranger"], [], [Format.CC, Format.LL]),
	"Ser Boltyn"	: Hero.new(48,  "Ser Boltyn, Breaker of Dawn"	  ,  417, 40, ["Warrior"], ["Light"], [Format.CC, Format.LL]),
	"Teklovossen"	: Hero.new(49,  "Teklovossen, Esteemed Magnate"	  ,  124, 40, ["Mechanologist"], [], [Format.CC, Format.LL]),
	"Tuffnut"		: Hero.new(50,  "Tuffnut, Bumbling Hulkster"	  ,    5, 40, ["Brute"], ["Revered"], [Format.CC, Format.LL]),
	"Uzuri"			: Hero.new(51,  "Uzuri, Switchblade"			  ,  405, 40, ["Assassin"], [], [Format.CC, Format.LL]),
	"Valda"			: Hero.new(52,  "Valda, Seismic Impact"			  ,   28, 40, ["Guardian"], [], [Format.CC, Format.LL]),
	"Verdance"		: Hero.new(53,  "Verdance, Thorn of the Rose"	  , 1019, 40, ["Wizard"], ["Elemental"], [Format.LL]),
	"Victor"		: Hero.new(54,  "Victor Goldmane, High and Mighty", 1033, 40, ["Guardian"], [], [Format.LL]),
	"Viserai"		: Hero.new(55,  "Viserai, Rune Blood"			  , 1016, 40, ["Runeblade"], [], [Format.LL]),
	"ViseraiF"		: Hero.new(56,  "Viserai, the Forsaken"			  ,    0, 40, ["Runeblade"], ["Shadow"], [Format.CC, Format.LL]),
	"Vynnset"		: Hero.new(57,  "Vynnset, Iron Maiden"			  ,  296, 40, ["Runeblade"], ["Shadow"], [Format.CC, Format.LL]),
	"Zen"			: Hero.new(58,  "Zen, Tamer of Purpose"			  , 1000, 40, ["Ninja"], ["Mystic"], [Format.LL]),
	"Zyggy"			: Hero.new(59,  "Zyggy Starlight"				  ,   13, 40, ["Illusionist"], ["Lightning"], [Format.CC, Format.LL]),
##### Young #####
	"YArakni"		: Hero.new(60,  "Arakni",						 	0, 20, ["Assassin"], [], [Format.UPF, Format.SAGE]),
	"YArakniS"		: Hero.new(61,  "Arakni, Solitary Confinement",		0, 19, ["Assassin"], [], [Format.UPF, Format.SAGE]),
	"YArakniW"		: Hero.new(62,  "Arakni, Web of Deceit",			0, 20, ["Assassin"], ["Chaos"], [Format.UPF, Format.SAGE]),
	"YAurora"		: Hero.new(63,  "Aurora",							0, 20, ["Runeblade"], ["Elemental"], [Format.UPF, Format.SAGE]),
	"YAuroraE"		: Hero.new(64,  "Aurora, Emissary of Lightning",	0, 20, ["Runeblade"], ["Lightning"], [Format.UPF, Format.SAGE]),
	"YAzalea"		: Hero.new(65,  "Azalea",							0, 20, ["Ranger"], [], [Format.UPF, Format.SAGE]),
	"YBaalghor"		: Hero.new(66,  "Baalghor, Omen of the End",		0, 33, [], ["Shadow"], [Format.UPF, Format.SAGE]),
	"YBenji"		: Hero.new(67,  "Benji, the Piercing Wind",			0, 17, ["Ninja"], [], [Format.UPF, Format.SAGE]),
	"YBetsy"		: Hero.new(68,  "Betsy",							0, 20, ["Guardian"], [], [Format.UPF, Format.SAGE]),
	"YBlaze"		: Hero.new(69,  "Blaze, Firemind",					0, 17, ["Wizard"], [], [Format.UPF, Format.SAGE]),
	"YBoltyn"		: Hero.new(70,  "Boltyn",							0, 20, ["Warrior"], ["Light"], [Format.UPF, Format.SAGE]),
	"YBravo"		: Hero.new(71,  "Bravo",							0, 20, ["Guardian"], [], [Format.UPF, Format.SAGE]),
	"YFlavo"		: Hero.new(72,  "Bravo, Flattering Showman",		0, 20, ["Guardian"], [], [Format.UPF, Format.SAGE]),
	"YBrevant"		: Hero.new(73,  "Brevant, Civic Protector",			0, 20, ["Guardian"], [], [Format.UPF]),
	"YBriar"		: Hero.new(74,  "Briar",							0, 20, ["Runeblade"], ["Elemental"], [Format.UPF]),
	"YChane"		: Hero.new(75,  "Chane",							0, 20, ["Runeblade"], ["Shadow"], [Format.UPF]),
	"YCindra"		: Hero.new(76,  "Cindra",							0, 20, ["Ninja"], ["Draconic", "Royal"], [Format.UPF, Format.SAGE]),
	"YDash"			: Hero.new(77,  "Dash",								0, 20, ["Mechanologist"], [], [Format.UPF, Format.SAGE]),
	"YDashD"		: Hero.new(78,  "Dash, Database",					0, 18, ["Mechanologist"], [], [Format.UPF, Format.SAGE]),
	"YDataDoll"		: Hero.new(79,  "Data Doll MKII",					0, 20, ["Mechanologist"], [], [Format.UPF, Format.SAGE]),
	"YDorinthea"	: Hero.new(80,  "Dorinthea",						0, 20, ["Warrior"], [], [Format.UPF, Format.SAGE]),
	"YDorintheaQ"	: Hero.new(81,  "Dorinthea, Quicksilver Prodigy",	0, 20, ["Warrior"], [], [Format.UPF, Format.SAGE]),
	"YMortimer"		: Hero.new(82,  "Dr. Mortimer",						0, 20, ["Assassin"], [], [Format.UPF, Format.SAGE]),
	"YDromai"		: Hero.new(83,  "Dromai",							0, 20, ["Illusionist"], ["Draconic"], [Format.UPF, Format.SAGE]),
	"YEmperor"		: Hero.new(84,  "Emperor, Dracai of Aesir",			0, 15, ["Wizard", "Warrior"], ["Draconic", "Royal"], [Format.UPF]),
	"YEnigma"		: Hero.new(85,  "Enigma",							0, 20, ["Illusionist"], ["Mystic"], [Format.UPF, Format.SAGE]),
	"YEnigmaN"		: Hero.new(86,  "Enigma, New Moon",					0, 20, ["Illusionist"], ["Mystic"], [Format.UPF]),
	"YFai"			: Hero.new(87,  "Fai",								0, 20, ["Ninja"], ["Draconic"], [Format.UPF, Format.SAGE]),
	"YFang"			: Hero.new(88,  "Fang",								0, 20, ["Warior"], ["Draconic"], [Format.UPF, Format.SAGE]),
	"YFlorian"		: Hero.new(89,  "Florian",							0, 20, ["Runeblade"], ["Elemental"], [Format.UPF, Format.SAGE]),
	"YFrankie"		: Hero.new(90,  "Frankie, Make Ends Meat",			0, 20, ["Necromancer"], [], [Format.UPF]),
	"YGenis"		: Hero.new(91,  "Genis Wotchuneed",					0, 20, ["Merchant"], [], [Format.UPF]),
	"YGravy"		: Hero.new(92,  "Gravy Bones",						0, 20, ["Necromancer", "Pirate"], [], [Format.UPF, Format.SAGE]),
	"YHala"			: Hero.new(93,  "Hala",								0, 20, ["Warrior"], [], [Format.UPF, Format.SAGE]),
	"YIra"			: Hero.new(94,  "Ira, Crimson Haze",				0, 20, ["Ninja"], [], [Format.UPF, Format.SAGE]),
	"YIyslander"	: Hero.new(95,  "Iyslander",						0, 18, ["Wizard"], ["Elemental"], [Format.UPF, Format.SAGE]),
	"YKano"			: Hero.new(96,  "Kano",								0, 15, ["Wizard"], [], [Format.UPF, Format.SAGE]),
	"vKassai"		: Hero.new(97,  "Kassai",							0, 20, ["Warrior"], [], [Format.UPF, Format.SAGE]),
	"YKassaiCS"		: Hero.new(98,  "Kassai, Cintari Sellsword",		0, 20, ["Warrior"], [], [Format.UPF, Format.SAGE]),
	"YKatsu"		: Hero.new(99,  "Katsu",							0, 20, ["Ninja"], [], [Format.UPF, Format.SAGE]),
	"YKavdaen"		: Hero.new(100, "Kavdaen, Trader of Skins",			0, 20, ["Merchant"], [], [Format.UPF, Format.SAGE]),
	"YKayo"			: Hero.new(101, "Kayo",								0, 20, ["Brute"], [], [Format.UPF, Format.SAGE]),
	"YKayoBR"		: Hero.new(102, "Kayo, Berserker Runt",				0, 19, ["Brute"], [], [Format.UPF, Format.SAGE]),
	"YKayoSA"		: Hero.new(103, "Kayo, Strong-arm",					0, 20, ["Brute"], ["Reviled"], [Format.UPF, Format.SAGE]),
	"YKilljoy"		: Hero.new(104, "Killjoy, the Crooked Blade",		0, 20, ["Warrior"], ["Reviled"], [Format.UPF, Format.SAGE]),
	"YLevia"		: Hero.new(105, "Levia",							0, 20, ["Brute"], ["Shadow"], [Format.UPF, Format.SAGE]),
	"YLexi"			: Hero.new(106, "Lexi",								0, 20, ["Ranger"], ["Elemental"], [Format.UPF, Format.SAGE]),
	"YLyath"		: Hero.new(107, "Lyath Goldmane",					0, 20, ["Guardian"], ["Reviled"], [Format.UPF, Format.SAGE]),
	"YMalice"		: Hero.new(108, "Malice",							0, 20, ["Necromancer"], ["Shadow"], [Format.UPF, Format.SAGE]),
	"YMarlynn"		: Hero.new(109, "Marlynn",							0, 20, ["Ranger", "Pirate"], [], [Format.UPF, Format.SAGE]),
	"YMaxx"			: Hero.new(110, "Maxx Nitro",						0, 20, ["Mechanologist"], [], [Format.UPF, Format.SAGE]),
	"YMelody"		: Hero.new(111, "Melody, Sing-along",				0, 20, ["Bard"], [], [Format.UPF]),
	"YNuu"			: Hero.new(112, "Nuu",								0, 20, ["Assassin"], ["Mystic"], [Format.UPF, Format.SAGE]),
	"YOldhim"		: Hero.new(113, "Oldhim",							0, 20, ["Guardian"], ["Elemental"], [Format.UPF]),
	"YOlympia"		: Hero.new(114, "Olympia",							0, 20, ["Warrior"], [], [Format.UPF, Format.SAGE]),
	"YOscilio"		: Hero.new(115, "Oscilio",							0, 18, ["Wizard"], ["Elemental"], [Format.UPF]),
	"YOscilioSA"	: Hero.new(116, "Oscilio, Scion of the Third Age",	0, 19, ["Wizard"], ["Lightning"], [Format.UPF, Format.SAGE]),
	"YPleiades"		: Hero.new(117, "Pleiades",							0, 20, ["Guardian"], ["Revered"], [Format.UPF, Format.SAGE]),
	"YPrism"		: Hero.new(118, "Prism",							0, 20, ["Illusionist"], ["Light"], [Format.UPF, Format.SAGE]),
	"YPrismAT"		: Hero.new(119, "Prism, Advent of Thrones",			0, 16, ["Illusionist"], ["Light"], [Format.UPF, Format.SAGE]),
	"YTeklovossenP"	: Hero.new(120, "Professor Teklovossen",			0, 20, ["Mechanologist"], [], [Format.UPF, Format.SAGE]),
	"YPuffin"		: Hero.new(121, "Puffin",							0, 20, ["Mechanologist", "Pirate"], [], [Format.UPF, Format.SAGE]),
	"YRhinar"		: Hero.new(122, "Rhinar",							0, 20, ["Brute"], [], [Format.UPF, Format.SAGE]),
	"YRiptide"		: Hero.new(123, "Riptide",							0, 19, ["Ranger"], [], [Format.UPF, Format.SAGE]),
	"YScurv"		: Hero.new(124, "Scurv, Stowaway",					0, 20, ["Pirate", "Thief"], [], [Format.UPF, Format.SAGE]),
	"YShiyana"		: Hero.new(125, "Shiyana, Diamond Gemini",			0, 20, ["Shapeshifter"], [], [Format.UPF]),
	"YSquizzy"		: Hero.new(126, "Squizzy & Floof",					0, 20, ["Merchant"], [], [Format.UPF]),
	"YTaylor"		: Hero.new(127, "Taylor",							0, 18, ["Shapeshifter"], [], [Format.UPF]),
	"YTeklovossen"	: Hero.new(128, "Teklovossen",						0, 20, ["Mechanologist"], [], [Format.UPF, Format.SAGE]),
	"YTerra"		: Hero.new(129, "Terra",							0, 20, ["Guardian"], ["Elemental"], [Format.UPF, Format.SAGE]),
	"YTuffnut"		: Hero.new(130, "Tuffnut",							0, 20, ["Brute"], ["Revered"], [Format.UPF, Format.SAGE]),
	"YUzuri"		: Hero.new(131, "Uzuri",							0, 20, ["Assassin"], [], [Format.UPF, Format.SAGE]),
	"YValda"		: Hero.new(132, "Valda Brightaxe",					0, 21, ["Guardian"], [], [Format.UPF, Format.SAGE]),
	"YVerdance"		: Hero.new(133, "Verdance",							0, 20, ["Wizard"], ["Elemental"], [Format.UPF, Format.SAGE]),
	"YVictor"		: Hero.new(134, "Victor Goldmane",					0, 20, ["Guardian"], [], [Format.UPF, Format.SAGE]),
	"YViserai"		: Hero.new(135, "Viserai",							0, 20, ["Runeblade"], [], [Format.UPF, Format.SAGE]),
	"YViseraiB"		: Hero.new(136, "Viserai, Between Worlds",			0, 20, ["Runeblade"], ["Shadow"], [Format.UPF, Format.SAGE]),
	"YVynnset"		: Hero.new(137, "Vynnset",							0, 20, ["Runeblade"], ["Shadow"], [Format.UPF, Format.SAGE]),
	"YYoji"			: Hero.new(138, "Yoji, Royal Protector",			0, 22, ["Guardian"], [], [Format.UPF, Format.SAGE]),
	"YYorick"		: Hero.new(139, "Yorick, Weaver of Tales",			0, 20, ["Bard"], [], [Format.UPF]),
	"YZane"			: Hero.new(140, "Zane, Broadly Beloved",			0, 20, ["Warrior"], ["Revered"], [Format.UPF, Format.SAGE]),
	"YZen"			: Hero.new(141, "Zen",								0, 20, ["Ninja"], ["Mystic"], [Format.UPF, Format.SAGE]),
	"YZyggy"		: Hero.new(142, "Zyggy",							0, 20, ["Illusionist"], ["Lightning"], [Format.UPF, Format.SAGE]),
}


func _get_class(_name: String) -> Class:
	if Data.classes.find_key(_name):
		return Data.classes[_name]
	push_error("Class not found")
	return Class.new(-1, "")

func _get_talent(_name: String) -> Talent:
	if Data.talents.find_key(_name):
		return Data.talents[_name]
	push_error("Talent not found")
	return Talent.new(-1, "")

func _get_hero(_name: String) -> Hero:
	for k in Data._Hero.keys():
		if k == _name:
			return Data._Hero[_name]
			break
	push_error("Hero not found")
	return Hero.new(-1, "", -1, -1, [], [], [])
